/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// noinspection JSUnusedGlobalSymbols
// Generated by unplugin-auto-import
export {}
declare global {
  const Snackbar: typeof import('@varlet/ui')['Snackbar']
  const StyleProvider: typeof import('@varlet/ui')['StyleProvider']
}
